version: '3.8'
services:
  dev-database:
    image: postgres:16.2
    container_name: dev-database
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin777
      POSTGRES_DB: testdb
    networks:
      - nestjs-network
networks:
  nestjs-network:
  
